[package]
name = "simple_rust_server"
version = "0.1.0"
authors = ["Adam Bates <adam@adambates.ca>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
